import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { asc, eq, inArray } from "drizzle-orm";

import { auth } from "@/lib/adapters";
import { db, schema } from "@/lib/db";
import { seatCheckInUrl, seatQrSvg } from "@/lib/qr";
import { Card, CardBody } from "@/components/ui/primitives";

export const metadata: Metadata = { title: "Desk QR codes" };
export const dynamic = "force-dynamic";

/**
 * The printable sheet: one QR sticker per bookable desk.
 *
 * The artefact that actually goes on 141 desks, so it is built for a printer
 * rather than a screen — 12 to an A4 page, cut lines implied by the hairline
 * borders, and the URL printed in full underneath each code so a sticker that
 * will not scan is still usable and so anybody can see there is nothing secret
 * in it.
 *
 * The SVG is generated server-side and inlined. That is deliberate: no client
 * JavaScript, no runtime fetch, and nothing that can fail halfway through a
 * print job on an office printer.
 *
 * Only bookable desks get a code. A fixed desk has an owner and needs no
 * check-in; a blocked one should not invite anybody to sit at it.
 */
export default async function Page() {
  const viewer = await auth().currentUser();
  // Server-side, like /admin/floor-plan: the hidden nav item is a courtesy, not
  // a permission check.
  if (!viewer?.isAdmin) notFound();

  const seats = await db()
    .select({
      seatCode: schema.seats.seatCode,
      bay: schema.seats.bay,
      zoneCode: schema.zones.code,
    })
    .from(schema.seats)
    .innerJoin(schema.zones, eq(schema.seats.zoneId, schema.zones.id))
    .where(inArray(schema.seats.status, ["bookable"]))
    .orderBy(asc(schema.seats.seatCode));

  const codes = await Promise.all(
    seats.map(async (seat) => ({
      ...seat,
      url: seatCheckInUrl(seat.seatCode),
      svg: await seatQrSvg(seat.seatCode),
    })),
  );

  return (
    <div className="space-y-6">
      <header className="print:hidden">
        <h1 className="text-2xl">Desk QR codes</h1>
        <p className="mt-1 max-w-2xl text-sm text-ink-muted">
          One sticker per bookable desk, {codes.length} in all. Print this page and
          cut along the hairlines. Scanning a sticker opens a check-in page for
          whoever is signed in — the code itself carries no identity, so a
          photograph of one grants nothing.
        </p>
      </header>

      <Card className="print:hidden">
        <CardBody className="text-sm text-ink-muted">
          <p>
            <strong className="font-medium text-ink">Why these matter.</strong> A
            door swipe proves somebody reached the floor. It does not prove they
            used a particular desk — so occupancy built on swipes alone cannot
            tell a full floor from a half-full one, which is the number the
            partners are asking for. These give seat-level evidence and remove
            the dependency on an access-control vendor we cannot integrate with.
          </p>
        </CardBody>
      </Card>

      <div className="qr-sheet grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">
        {codes.map((seat) => (
          <figure
            key={seat.seatCode}
            className="qr-card flex break-inside-avoid flex-col items-center gap-2 rounded-sm border border-hairline bg-surface px-3 py-4 text-center"
          >
            <div
              className="w-full max-w-[7rem] [&>svg]:h-auto [&>svg]:w-full"
              // Generated by the `qrcode` package from a URL this file builds;
              // there is no user input anywhere in the string.
              dangerouslySetInnerHTML={{ __html: seat.svg }}
              aria-hidden="true"
            />
            <figcaption className="space-y-0.5">
              <p className="seat-code text-base text-ink">{seat.seatCode}</p>
              <p className="text-[10px] text-ink-subtle">
                Zone {seat.zoneCode} · bay {seat.bay}
              </p>
              <p className="text-[8px] break-all text-ink-subtle">{seat.url}</p>
            </figcaption>
          </figure>
        ))}
      </div>
    </div>
  );
}
